### ISSUE TITLE
Feature: I forgot my username / password

### ISSUE THREAD

**Issue by russellballestrini** [newspipe/newspipe#39]
Feature: I forgot my username / password

Actually I really did, I signed up a couple weeks ago and I forgot what I used and now I'm not sure how to proceeded.

**Comment by cedricbonhomme** [comment]
I recently removed this feature because the database no longer stores email address (694e8a2a264c15ff95db66b8cf86ca84aa23ba88). The email address is only asked when creating an account, for the account validation. But it is no more store in the database.

I thought about this problem. I can implement a security question. But I don't like this system.
Actually the thing to do, is to contact the platform admin (in this case me...) with the email address here:
https://www.newspipe.org/about

The best thing you can do is to create again your account.
